### ISSUE TITLE
Wrap existing handler delegation into separate Verticles

### ISSUE THREAD

**Issue by zznate** [zznate/intravert-ug#209]
The initial split will consist of:
- mutation
- selection
- meta
- dynamic

This will allow us to adjust threading accordingly. Initial thread counts will be hardcoded in o.u.v.s.IntravertCassandraServer. Config of such will be handled under #209

**Comment by edwardcapriolo** [comment]
We should start with a proof of concept, possibly the set handler. Move this into a verticle.

**Comment by zznate** [comment]
Agreed. We'll start with everything as-is, except sethandler in new verticle.

**Comment by edwardcapriolo** [comment]
I have been playing around with this for a couple days now. Not having much luck. I think we are better off with modules then verticles, modules seem to have more of what we want. Particularily when it comes to version-ing and reloadabilty. The only big difference I see is that a verticle can be a "worker" verticle or no, but I am not clear if our things should be workers or not. So I am proposing we go with the module approach vs the vertical one.

**Comment by edwardcapriolo** [comment]
It turns out to be a real pain in the arse to package modules and run them in a unit test.

https://github.com/thmarx/vert.x-busmod-redis/blob/master/build.gradle

A

**Comment by edanuff** [comment]
with Vert.x 2.0, which I assume we're targeting, there's no need to do this stuff in Gradle.  Suggest you do it the Maven way - https://github.com/vert-x/vert.x/wiki/Vert.x-2.0---Developing-Vert.x-with-Maven - and if you generate your module using the Maven artifact, it generates an assortment of unit tests for testing modules and verticles.

**Comment by edwardcapriolo** [comment]
2.0 is not released yet, and it is not in maven yet. So for the out of the box experience we have been using 1.3.X-final. I agree though we should switch to 2.0 because otherwise modules always try to load from a vertx github page :)

**Comment by edanuff** [comment]
2.0 is in Maven Central now http://search.maven.org/#browse%7C1046654777

**Comment by edwardcapriolo** [comment]
I have studied vertx long and hard. The long and short of it is this approach to modularize or verticalize the different intravert operations  is the wrong one. Here is why:

1)
EventLoop programming is not right for cassandra. The vertx documentation makes the distinction about work that should and should not be done on the event loop. You can argue that mutate operations are fine for the event loop and I would agree. For the memcaches and redis's of the world all their operations likely offer predictable performance less < 1 ms. But read and slice operations have to live in the so-called worker verticles, the worker verticles are no more then background executor service.

2) callback style operations make sense for SOA type operations, but they are not really an efficient or easy way to hand a request between stages on the server side. By efficient I mean programmer efficient and the cost of copying objects between actors. Also not being able to block up the event loop severly limits what you can do in a callback anyway.

3) I have looked at the mongo-persistors redis-persister modules and they are essentially build like intravert v1 was built. 1 big case statement as a worker module

4) writing and testing modules is a pain in the arse to put it mildly, as is debugging where something went wrong in a series of sends, replys and callback

Still what we did was good. Johns work to put everything on a event bus endpoint forced us to modularize our code.

There are good parts of vertx we are going to continue to use. None of the client code will be effected by this change.

We are still going to use vertx components. Namely the client itself as well as the http server. However the operations are going to be moduled in a seda style similar to c*.

Frankly I want to do something simplelike this. Intravert will be composed of a staticaly accessible map of thread pools. SetPool, GetPool, they may be fixed size or not. We can add handlers to the pool by name like we are doing now. The request will come in through the current json endpoint. We will wrap it in a context (SendIt in the below example).  and the processMessage method will move it between the stages. When it is done it gets sent back. If someone wants to experiment with vertx modules they can use them through the callables in the executor services or whatever.

{noformat}
public static void main (String [] args) throws InterruptedException, ExecutionException{
    final TestAct a = new TestAct();
    a.pools.put("stage1", Executors.newFixedThreadPool(10));
    a.pools.put("stage2", Executors.newFixedThreadPool(10));
    a.pools.put("stage3", Executors.newFixedThreadPool(10));

```
final SendIt s = new SendIt();
s.to = new ArrayList<String>();
s.to.add("stage1");
s.to.add("stage3");
s.message = "what up";
a.processMessage(s);

System.out.println(s.message);
```

  }

  public SendIt processMessage(final SendIt s){
    for (final String to: s.to){
      if (to.equalsIgnoreCase("stage1")){
        Callable<SendIt> c = new Callable<SendIt>(){
          public SendIt call() throws Exception {
            System.out.println(s.message);
            s.message+= "stage 1 complete";
            return s;
          }  
        };
        Future<SendIt> f = this.pools.get(to).submit(c);
        try {
          f.get(1000, TimeUnit.MILLISECONDS);
        } catch (InterruptedException | ExecutionException | TimeoutException e) {
          return s;
        }
      }
      if (to.equalsIgnoreCase("stage3")){
        Callable<SendIt> c = new Callable<SendIt>(){
          public SendIt call() throws Exception {
            System.out.println(s.message);
            s.message+= "stage 3 complete";
            return s;
          }  
        };
        Future<SendIt> f = this.pools.get(to).submit(c);
        try {
          f.get(1000, TimeUnit.MILLISECONDS);
        } catch (InterruptedException | ExecutionException | TimeoutException e) {
          return s;
        }
      }
    }
    return s;
  }
}

class SendIt{
  List<String> to;
  String message;

}
{noformat} 

We will retrofit the current handlers in same way so that we can move them to this new format without having to cannibalize them to much. If anyone has some better design ideas for doing the seda pool please contribute.

**Comment by zznate** [comment]
Give me a few to digest. We can make this work though. @edanuff thoughts?

**Comment by edanuff** [comment]
Some good points here, but I need to parse as well.  One thing that occurs
to me is that for something like this, using mod-rxvertx really is a must,
things will quickly descend into callback hell, which is what I feel you're
expressing in terms of debug-ability.

Ed

On Jun 2, 2013, at 10:25 AM, Nate McCall notifications@github.com wrote:

Give me a few to digest. We can make this work though.
@edanuffhttps://github.com/edanuffthoughts?

—
Reply to this email directly or view it on
GitHubhttps://github.com/zznate/intravert-ug/issues/209#issuecomment-18809925
.

**Comment by edwardcapriolo** [comment]
http://vertx.io/manual.html

An example of the former would be calling a third-party blocking database API from a verticle. In this case you don't have control of the client library you are using so you just have to block until you get the result back.

Another example would be a worker verticle which needs to do an intensive calculation like calculating Fibonacci numbers. In such a case the calculation could be done a little at a time on different circuits around the event loop, but this is awkward, and just a little bit silly ;)

For cases like these, vert.x allows you to mark a particular verticle instance as a worker verticle. A worker verticle differs from a normal verticle in that it is not assigned a vert.x event loop thread.....

<b>
instead it executes on a thread from an internal thread pool called the background pool. </b>

**Comment by edwardcapriolo** [comment]
I am just at the point where i feel anything outside of SEDA architecture is an over design. I have been researching something like RXVertx it is called the "promises api", these solutions seem to solve problems we are not having.

**Comment by edanuff** [comment]
I'm not following the nature of the problem, is this about the specific issue of splitting handlers into separate Verticles?  BTW, I think that RX is orthogonal to Promises - https://github.com/Netflix/RxJava/wiki - RX is solving the composition problem since callback programming gets a bit spaghetti-like quickly.

**Comment by edwardcapriolo** [comment]
the issue is that if you look at the vertx mongo or redis persister all
they are us a big case statement 1 module inplemntd as a worker module.

we are the only ones attempting to divide functionality across modules. I
do not see the point. It does not add scalability and it adds tons of
complexity.

So much complexity in fact that I have spent maybe the last 2-3 months
trying to fix features that worked in the old version that were broken when
we switched to callbacks and this event bus approach.

It has totally derailed what I wanted to do with the project.

**Comment by edwardcapriolo** [comment]
This is what I want to bring the code to. A simple non-event bus endpoint. That reads a request and moves it through the handlers wrapping a callable in a future. Please discuss.

``` java

package org.usergrid.vx.handler.http.payload;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import org.apache.cassandra.db.ConsistencyLevel;
import org.apache.cassandra.db.IMutation;
import org.apache.cassandra.db.RowMutation;
import org.apache.cassandra.db.filter.QueryPath;
import org.apache.cassandra.service.StorageProxy;
import org.apache.commons.lang.exception.ExceptionUtils;
import org.codehaus.jackson.JsonGenerationException;
import org.codehaus.jackson.JsonParseException;
import org.codehaus.jackson.map.JsonMappingException;
import org.codehaus.jackson.map.ObjectMapper;
import org.codehaus.jackson.map.SerializationConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.usergrid.vx.experimental.IntraOp;
import org.usergrid.vx.experimental.IntraReq;
import org.usergrid.vx.experimental.IntraRes;
import org.usergrid.vx.experimental.Operations;
import org.usergrid.vx.handler.IntraHandler;
import org.usergrid.vx.handler.PayloadRoutingHandler;
import org.usergrid.vx.handler.http.OperationsRequestHandler;
import org.usergrid.vx.handler.http.TimeoutHandler;
import org.usergrid.vx.server.operations.HandlerUtils;
import org.vertx.java.core.Handler;
import org.vertx.java.core.Vertx;
import org.vertx.java.core.buffer.Buffer;
import org.vertx.java.core.eventbus.Message;
import org.vertx.java.core.http.HttpServerRequest;
import org.vertx.java.core.json.JsonArray;
import org.vertx.java.core.json.JsonObject;

public class IntraHandlerJson implements Handler<HttpServerRequest> {
  private static Logger logger = LoggerFactory.getLogger(IntraHandlerJson.class);

  private static ObjectMapper mapper = new ObjectMapper();
  private static ObjectMapper indentObjectMapper = new ObjectMapper();

  static {
      indentObjectMapper.getSerializationConfig().set(SerializationConfig.Feature.INDENT_OUTPUT, true);
  }

  private final Vertx vertx;

  static Map<String,ExecutorService> stages = new HashMap<String,ExecutorService>();
  static Map<String,CallableBuilder> requestBuilder = new HashMap<String,CallableBuilder>();
  public IntraHandlerJson(Vertx vertx) {
    this.vertx = vertx;
    stages.put("SET", Executors.newScheduledThreadPool(10));
    requestBuilder.put("SET", new SetBuilder());
  }

  @Override
  public void handle(final HttpServerRequest request) {
    request.bodyHandler(new Handler<Buffer>() {
      @Override
      public void handle(Buffer buffer) {
        IntraReq req = null;
        try {
          req = mapper.readValue(buffer.getBytes(), IntraReq.class);
          RequestState state = new RequestState();
          state.request = req.toJson();
          executeRequest(state);
          request.response().end(mapper.writeValueAsString(state.res));
          if (logger.isDebugEnabled()) {
            logger.debug("IntraJsonHandler received payload: \n{}",
                    indentObjectMapper.writeValueAsString(req));
          }
        } catch (Exception ex) {
          ex.printStackTrace();
        }
      }
    });
    }

  private void executeRequest(RequestState rstate){
    JsonObject req = rstate.request;
    JsonArray operations = req.getArray(Operations.E);
    long startMillis = System.currentTimeMillis();

    for (int i = 0; i < operations.size(); i++) {
      final IntraOp operation = (IntraOp) operations.get(i);
      JsonObject op = new JsonObject(operation.getOp());
      operation.getOp().put(Operations.ID, i);
      Callable<Void> call = requestBuilder.get(operation.getType().toString()).build(op,rstate);
      Future<Void> f = stages.get(operation.getType().toString()).submit(call);
      try {
        f.get(5000, TimeUnit.MILLISECONDS);
      } catch (InterruptedException | ExecutionException | TimeoutException e) {
        e.printStackTrace();
      }
    }
  }

}

abstract class CallableBuilder {
   public Callable<Void> build(JsonObject operation, final RequestState req){
     return null;
   }
}

class SetBuilder extends CallableBuilder {
  public Callable<Void> build(final JsonObject operation, final RequestState req) {
    return new Callable<Void>() {

      @Override
      public Void call() throws Exception {

        try {
          System.out.println(operation.toString());
          Integer id = operation.getInteger(Operations.ID);
          JsonObject state = req.state;
          RowMutation rm = new RowMutation(
                  HandlerUtils.instance.determineKs(operation, state, null),
                  HandlerUtils.instance.byteBufferForObject(operation.getField(Operations.ROWKEY)));
          QueryPath qp = new QueryPath(HandlerUtils.instance.determineCf(operation, state, null),
                  null, HandlerUtils.instance.byteBufferForObject(operation
                          .getField(Operations.NAME)));
          Object val = operation.getField(Operations.VALUE);
          Integer ttl = operation.getInteger(Operations.TTL);
          if (ttl == null) {
            rm.add(qp, HandlerUtils.instance.byteBufferForObject(HandlerUtils.instance
                    .resolveObject(val)), System.nanoTime());
          } else {
            rm.add(qp, HandlerUtils.instance.byteBufferForObject(HandlerUtils.instance
                    .resolveObject(val)), System.nanoTime(), ttl);
          }
          List<IMutation> mutations = new ArrayList<IMutation>();
          mutations.add(rm);
          StorageProxy.mutate(mutations, ConsistencyLevel.ONE);

          req.res.getOpsRes().put(id, "OK");
        } catch (Exception ex) {
          ex.printStackTrace();
        }

        return null;
      }

    };
  }
}

class RequestState {
  JsonObject request;
  IntraRes res;
  JsonObject state;

  public RequestState(){
    res = new IntraRes();
    state =  new JsonObject()
      .putArray(Operations.COMPONENTS, new JsonArray()
        .add(Operations.NAME)
        .add(Operations.VALUE));
  }
}
```
