### ISSUE TITLE
Good Idea Bad Idea . Locking?

### ISSUE THREAD

**Issue by edwardcapriolo** [zznate/intravert-ug#27]
Does it make sense that now that we can performn n operations on the server  and async IO between Verticals that we do a lock, maybe working with a fast small heavily cached cf called LOCKS at quorum, or maybe a cf that is only local?

**Comment by zznate** [comment]
Eventually a good idea. But soon. We could graph the hard-won locking approach from the most recent hector. @tnine thoughts? (yeah I just ambushed you like that :)

**Comment by tnine** [comment]
LOL.   It depends....   The locking algorithm is optimized to only coordinate the first 10 clients contending for a lock.  The rest do not participate until they're advanced to the first 10 clients in the queue.  We shouldn't have any performance issues regardless of the number of locking clients. However, if a large number of clients contending for a lock increases, I'm concerned Cassandra may begin to become slow on the reads.   We should  turn on row caching to avoid this since the row size will generally be pretty small.

**Comment by edwardcapriolo** [comment]
Sorry did must have fat fingered the close button. @Todd I figured that since we can do multiple round-trips and we have asyn on the server the contention might be easier to deal with now since we can do work on behalf of the client but understood under heavy contention that particular algorithm can be an issue.

**Comment by edwardcapriolo** [comment]
> You may be interested in checking those out for more details:
> 
> http://snapwebsites.org/journal/2013/01/inter-process-inter-computer-lock-cassandra
> 
> http://snapwebsites.org/project/libqtcassandra
> 
> http://snapwebsites.org/mo_references_view/libQtCassandra-doc-0.4/classQtCassandra_1_1QCassandraLock.html#details

**Comment by tnine** [comment]
I'm going to try to tackle this over the weekend.  I need to get over the curve and get involved.

**Comment by edwardcapriolo** [comment]
I think a good implementation might be an atomic check and put as a user facing feature
