### ISSUE TITLE
Should GETREF be a type?

### ISSUE THREAD

**Issue by zznate** [zznate/intravert-ug#86]

**Comment by zznate** [comment]
My thinking here is that GETREF is an "implicit thing" regardless of the type, size, scope of the operation. 

For example, given the doc here: https://github.com/zznate/intravert-ug/wiki/GETREF and the following example from such:

```
req.add( IntraOp.setOp("rowb", "col2", IntraOp.getResRefOp(5, "value"))); //5
```

I think implicit access to whatever came before would make more sense in the context of what OpType is supposed to be. In other words, the above could be rewritten as:

```
req.add( IntraOp.setOp("rowb", "col2", ${5.value})); 
```

This may have been what @edwardcapriolo and @jsanda were talking about all along and perhaps I am just slow :)

Thoughts?

**Comment by jsanda** [comment]
This is in line with my thinking based off of the previous discussion with @edwardcapriolo. What wasn't clear to is whether or not GETREF should remain as an IntraOp. I can see pros/cons for both keeping and removing it. In the JSON test that I implemented, it is is still used. The server still expects a "type" key in the nested map with a value of "GETREF". Considering that, I think it may make sense keeping it as a type. On the negative side, it is not consistent with the other types. Things still seem pretty fluid so I do not have a strong opinion one way or the other at this point.

**Comment by edwardcapriolo** [comment]
I do not like majic strings like $4.value that need to be evaled just for this one use case.

ServiceProcessor can do what getref can (less clean but can do it ) so there is a thinking to remove getref all together.

In any case the important point here is that most of our unit tests skip the jackson mapping piece. They send ops directly to IntraService skipping jackson. So if @jsanda had to change it to get his test to work there is a good chance it was never working anyway because it never properly serialized. Thus I only care that the feature actually works, if it be a map or a type does not matter to me but it sounds like the map actually worked and the type did not.

**Comment by zznate** [comment]
Actually... are we just making this too hard? Why not just embed another op where the getref goes? Ie.:

```
{
    "type": "SET",
    "op": {
        "rowkey": "getref_test",
        "name": "col3",
        "value": {
              "type": "GET",
              "op": {
                   "rowkey": "getref_test",
                   "name": "col1"
              }
          }
    }
}
```

**Comment by edwardcapriolo** [comment]
That is how it was I thought. (John thinks jackson was not serializing this)

**Comment by zznate** [comment]
Scratch that - I was thinking of something different (getref being a wholly nested operation as opposed to "operation number 4") but that get's too ugly and doesnt work if you want "operation number 4" in your result object independantly.

**Comment by jsanda** [comment]
Jackson is serializing and deserializing it. The problem was that the GETREF object was getting deserialized into a Map, not an IntraOp. IntraService.resolveObject was expecting an IntraOp. Prior to the test I added in RawJsonITest, GetREF was only tested in IntraServiceITest which bypassed the issue altogether since it works directly at the Java API layer.

**Comment by edwardcapriolo** [comment]
I think it is working now so will close issue. I don't care what it is as long as it is working now. Someone can re-open if they have strong opionions and want to do a refactor.
